In [1]:
import numpy as np
import pandas as pd
import os
import sys

In [2]:
filename=r"C:\..\puzzle.xlsx"
grid = pd.read_excel(filename,header=None,index_col=False)
grid.fillna(0,inplace=True)
grid=np.matrix(grid.to_numpy(dtype='int'))

In [4]:
#function to check possiblity of inserstion based on rules of the game. Checks only one digit n at (x,y)
def possible(y,x,n):
    global grid
    if (grid[y:y+1,:]==n).any():
        return False
    if (grid[:,x:x+1]==n).any():
        return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    if (grid[y0:y0+3,x0:x0+3]==n).any():
        return False
    return True

In [8]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y,x]==0:
                for n in range(10):
                    if possible(y,x,n):
                        grid[y,x]=n
                        solve()
                        grid[y,x]=0
                return
    print(grid)
    sys.exit

In [9]:
solve()

[[1 8 4 3 9 6 7 2 5]
 [9 3 5 2 4 7 1 6 8]
 [6 7 2 1 5 8 3 4 9]
 [5 6 9 7 1 2 4 8 3]
 [7 4 3 6 8 9 5 1 2]
 [2 1 8 5 3 4 9 7 6]
 [8 9 1 4 2 5 6 3 7]
 [4 5 6 8 7 3 2 9 1]
 [3 2 7 9 6 1 8 5 4]]
